import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783093773416 implements MigrationInterface {
    name = 'InitialSchema1783093773416'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'editor', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'suspended', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255), "username" character varying(100) NOT NULL, "avatar_url" text, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "email_verified_at" TIMESTAMP, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "device_info" character varying(255), "ip_address" character varying(45), "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "user_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "theme" character varying(20) NOT NULL DEFAULT 'dark', "language" character varying(10) NOT NULL DEFAULT 'vi', "favorite_symbols" text, "notification_settings" jsonb, "timezone" character varying(50) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_458057fa75b66e68a275647da2" UNIQUE ("user_id"), CONSTRAINT "PK_e8cfb5b31af61cd363a6b6d7c25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_458057fa75b66e68a275647da2" ON "user_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ml_models_asset_type_enum" AS ENUM('crypto', 'forex', 'commodity', 'index')`);
        await queryRunner.query(`CREATE TYPE "public"."ml_models_target_timeframe_enum" AS ENUM('m1', 'm5', 'm15', 'h1', 'h4', 'd1')`);
        await queryRunner.query(`CREATE TYPE "public"."ml_models_status_enum" AS ENUM('staging', 'production', 'deprecated')`);
        await queryRunner.query(`CREATE TABLE "ml_models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "model_type" character varying(50) NOT NULL, "asset_type" "public"."ml_models_asset_type_enum" NOT NULL, "target_timeframe" "public"."ml_models_target_timeframe_enum" NOT NULL, "version" character varying(20) NOT NULL, "status" "public"."ml_models_status_enum" NOT NULL DEFAULT 'staging', "artifact_path" text NOT NULL, "training_dataset_range" character varying(100), "metrics" jsonb, "trained_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7844bc6f33c90e0e1451bbdc0a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9de8e07593325e4dce1f0c73a" ON "ml_models" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11b873c6a08fbd8bacf23558bf" ON "ml_models" ("name", "version") `);
        await queryRunner.query(`CREATE TYPE "public"."assets_asset_type_enum" AS ENUM('crypto', 'forex', 'commodity', 'index')`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "symbol" character varying(20) NOT NULL, "display_name" character varying(100) NOT NULL, "asset_type" "public"."assets_asset_type_enum" NOT NULL, "base_currency" character varying(10), "quote_currency" character varying(10), "exchange_source" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b4bd5b9c6fe49cd3b4342fb91" ON "assets" ("symbol") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaa6c65fe7cf634aa3d80f317d" ON "assets" ("asset_type") `);
        await queryRunner.query(`CREATE TYPE "public"."predictions_predicted_label_enum" AS ENUM('up', 'down', 'sideways')`);
        await queryRunner.query(`CREATE TYPE "public"."predictions_actual_label_enum" AS ENUM('up', 'down', 'sideways')`);
        await queryRunner.query(`CREATE TABLE "predictions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "model_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "predicted_at" TIMESTAMP NOT NULL, "target_time" TIMESTAMP NOT NULL, "predicted_label" "public"."predictions_predicted_label_enum" NOT NULL, "confidence" numeric(5,4) NOT NULL, "features_snapshot" jsonb, "actual_label" "public"."predictions_actual_label_enum", "is_correct" boolean, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b92c9e4db595214b289f5e28adc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f27be35e654b00363e7ae5c78f" ON "predictions" ("model_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9128d7a79e536a2896637109ed" ON "predictions" ("target_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_c394ecc1e8fa58f6580bf66afa" ON "predictions" ("asset_id", "predicted_at") `);
        await queryRunner.query(`CREATE TYPE "public"."trade_suggestions_direction_enum" AS ENUM('long', 'short')`);
        await queryRunner.query(`CREATE TYPE "public"."trade_suggestions_status_enum" AS ENUM('open', 'closed_tp', 'closed_sl', 'closed_manual', 'expired')`);
        await queryRunner.query(`CREATE TABLE "trade_suggestions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prediction_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "direction" "public"."trade_suggestions_direction_enum" NOT NULL, "entry_price" numeric(20,8) NOT NULL, "stop_loss" numeric(20,8) NOT NULL, "take_profit" numeric(20,8) NOT NULL, "risk_reward_ratio" numeric(6,2), "rationale" text NOT NULL, "disclaimer_shown" boolean NOT NULL DEFAULT true, "status" "public"."trade_suggestions_status_enum" NOT NULL DEFAULT 'open', "closed_price" numeric(20,8), "closed_at" TIMESTAMP, "pnl_percent" numeric(8,4), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02a42911e8b6a9546b3498c4c91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c2807b88e83a63424931813a8b" ON "trade_suggestions" ("asset_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2192c23b5304d5b5c91a0188c7" ON "trade_suggestions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a09a50a76cb6216696c834f9d" ON "trade_suggestions" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."user_suggestion_interactions_action_enum" AS ENUM('viewed', 'saved', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "user_suggestion_interactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "suggestion_id" uuid NOT NULL, "action" "public"."user_suggestion_interactions_action_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0ab941154fbf2f2a31b043b9997" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5b41340eb4bba9fd21fab3524" ON "user_suggestion_interactions" ("user_id", "suggestion_id") `);
        await queryRunner.query(`CREATE TYPE "public"."oauth_accounts_provider_enum" AS ENUM('google', 'github')`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" "public"."oauth_accounts_provider_enum" NOT NULL, "provider_user_id" character varying(255) NOT NULL, "access_token" text, "refresh_token" text, "expires_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710a81523f515b78f894e33bb10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ea7720e04e3ae1278575c3159c" ON "oauth_accounts" ("provider", "provider_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."news_sources_source_type_enum" AS ENUM('rss', 'api', 'scraper')`);
        await queryRunner.query(`CREATE TABLE "news_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "source_type" "public"."news_sources_source_type_enum" NOT NULL, "feed_url" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "fetch_interval_minutes" integer NOT NULL DEFAULT '15', "last_fetched_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afc653c2b8933edb29e2eb7e3fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "news_articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "source_id" uuid NOT NULL, "title" character varying(500) NOT NULL, "summary" text, "original_url" text NOT NULL, "thumbnail_url" text, "published_at" TIMESTAMP NOT NULL, "sentiment_score" numeric(4,3), "related_assets" uuid array, "is_featured" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca1b67b1b6b2c382317bbd769dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a18c32abffd704bb30dd82d8d" ON "news_articles" ("source_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_77c25997a64e1cc75db6f0cfdf" ON "news_articles" ("original_url") `);
        await queryRunner.query(`CREATE INDEX "IDX_b851c5ab8c02be5814e137be83" ON "news_articles" ("published_at") `);
        await queryRunner.query(`CREATE TABLE "news_article_assets" ("news_article_id" uuid NOT NULL, "asset_id" uuid NOT NULL, CONSTRAINT "PK_23355bec9f022d8a4b38a491424" PRIMARY KEY ("news_article_id", "asset_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."price_alerts_condition_enum" AS ENUM('above', 'below')`);
        await queryRunner.query(`CREATE TYPE "public"."price_alerts_status_enum" AS ENUM('active', 'triggered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "price_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "condition" "public"."price_alerts_condition_enum" NOT NULL, "target_price" numeric(20,8) NOT NULL, "status" "public"."price_alerts_status_enum" NOT NULL DEFAULT 'active', "triggered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_125caf0cfa6219ed3ea03646608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "watchlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "asset_id" uuid NOT NULL, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa3c717b50a10f7a435c65eda5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_13f381b5af2e4065063d97cdd7" ON "watchlists" ("user_id", "asset_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ohlcv_candles_timeframe_enum" AS ENUM('m1', 'm5', 'm15', 'h1', 'h4', 'd1')`);
        await queryRunner.query(`CREATE TABLE "ohlcv_candles" ("id" BIGSERIAL NOT NULL, "asset_id" uuid NOT NULL, "timeframe" "public"."ohlcv_candles_timeframe_enum" NOT NULL, "open_time" TIMESTAMP NOT NULL, "open" numeric(20,8) NOT NULL, "high" numeric(20,8) NOT NULL, "low" numeric(20,8) NOT NULL, "close" numeric(20,8) NOT NULL, "volume" numeric(24,8) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d19b67717b762bd73b268b9c02c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6cc46de572ad37ba5f5751001" ON "ohlcv_candles" ("open_time") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_candle_unique" ON "ohlcv_candles" ("asset_id", "timeframe", "open_time") `);
        await queryRunner.query(`CREATE TABLE "kb_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "category" character varying(100), "content" text NOT NULL, "source_reference" text, "version" integer NOT NULL DEFAULT '1', "is_published" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_14ad41415f09ecb8f042d78422a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "kb_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "chunk_index" integer NOT NULL, "content" text NOT NULL, "vector_id" character varying(255), "token_count" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de84c3fce0c1a29928e98441cd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_06f082ac79ac86cbb475e1a8d5" ON "kb_chunks" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_65fffed6d159417beffa3cfb00" ON "kb_chunks" ("vector_id") `);
        await queryRunner.query(`CREATE TABLE "chat_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "title" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efc151a4aafa9a28b73dedc485f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fa209cf48ae975a109366542a" ON "chat_sessions" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_role_enum" AS ENUM('user', 'assistant', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_feedback_enum" AS ENUM('up', 'down', 'none')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "session_id" uuid NOT NULL, "role" "public"."chat_messages_role_enum" NOT NULL, "content" text NOT NULL, "retrieved_chunk_ids" uuid array, "model_used" character varying(100), "latency_ms" integer, "token_usage" integer, "feedback" "public"."chat_messages_feedback_enum", "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0672782561e44d43febcfba298" ON "chat_messages" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_52d89390506ed998a56a73c04c" ON "chat_messages" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."economic_events_impact_level_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TABLE "economic_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "country_code" character varying(5) NOT NULL, "event_name" character varying(255) NOT NULL, "impact_level" "public"."economic_events_impact_level_enum" NOT NULL, "event_time" TIMESTAMP NOT NULL, "actual_value" character varying(50), "forecast_value" character varying(50), "previous_value" character varying(50), "unit" character varying(20), "source" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f10b9c707f4f1d05d356ed4ceac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_966b24173414783279e5ed1d85" ON "economic_events" ("event_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2bb2cd3da42b56a12729b919d" ON "economic_events" ("country_code", "impact_level") `);
        await queryRunner.query(`CREATE TABLE "external_api_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying(100) NOT NULL, "endpoint" character varying(255), "request_count" integer NOT NULL DEFAULT '1', "window_date" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_35040157a58d0dd459817b51b85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4578235c4831ec7f89308d4c8" ON "external_api_usage" ("provider", "window_date") `);
        await queryRunner.query(`CREATE TABLE "api_request_logs" ("id" BIGSERIAL NOT NULL, "user_id" uuid, "endpoint" character varying(255) NOT NULL, "method" character varying(10) NOT NULL, "status_code" integer, "latency_ms" integer, "ip_address" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fca5e76fc039cd1cb8f67374cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af11df5cf61163ea71b7f54f51" ON "api_request_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_88102539f457e6b871d794bf2d" ON "api_request_logs" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_preferences" ADD CONSTRAINT "FK_458057fa75b66e68a275647da2e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_f27be35e654b00363e7ae5c78fd" FOREIGN KEY ("model_id") REFERENCES "ml_models"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predictions" ADD CONSTRAINT "FK_e6cbd271f04a4997030d2632cf3" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_suggestions" ADD CONSTRAINT "FK_d41e829364b231f5f11327ab645" FOREIGN KEY ("prediction_id") REFERENCES "predictions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trade_suggestions" ADD CONSTRAINT "FK_c2807b88e83a63424931813a8b9" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_suggestion_interactions" ADD CONSTRAINT "FK_988a12e65c53a9692a54a54104f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_suggestion_interactions" ADD CONSTRAINT "FK_7355d10e8e25f0bba9d5eac300c" FOREIGN KEY ("suggestion_id") REFERENCES "trade_suggestions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_22a05e92f51a983475f9281d3b0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_articles" ADD CONSTRAINT "FK_7a18c32abffd704bb30dd82d8d2" FOREIGN KEY ("source_id") REFERENCES "news_sources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_article_assets" ADD CONSTRAINT "FK_a3ca2d90b92cb0d74e6ec063e85" FOREIGN KEY ("news_article_id") REFERENCES "news_articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_article_assets" ADD CONSTRAINT "FK_21d07060b26c5bedf54158c67d0" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_alerts" ADD CONSTRAINT "FK_e935431220d8759d650a506472f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_alerts" ADD CONSTRAINT "FK_5c9e7ca80a3fdbfd7f1d08b30c3" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchlists" ADD CONSTRAINT "FK_3e8bccad3dcd75fa977892c54bb" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchlists" ADD CONSTRAINT "FK_14ccdd74bf1a96986f6a9e1a4cd" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ohlcv_candles" ADD CONSTRAINT "FK_838d53efb207092b00460c0527d" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_chunks" ADD CONSTRAINT "FK_06f082ac79ac86cbb475e1a8d57" FOREIGN KEY ("document_id") REFERENCES "kb_documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_1fa209cf48ae975a109366542a5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_0672782561e44d43febcfba2984" FOREIGN KEY ("session_id") REFERENCES "chat_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_request_logs" ADD CONSTRAINT "FK_af11df5cf61163ea71b7f54f515" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "api_request_logs" DROP CONSTRAINT "FK_af11df5cf61163ea71b7f54f515"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_0672782561e44d43febcfba2984"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_1fa209cf48ae975a109366542a5"`);
        await queryRunner.query(`ALTER TABLE "kb_chunks" DROP CONSTRAINT "FK_06f082ac79ac86cbb475e1a8d57"`);
        await queryRunner.query(`ALTER TABLE "ohlcv_candles" DROP CONSTRAINT "FK_838d53efb207092b00460c0527d"`);
        await queryRunner.query(`ALTER TABLE "watchlists" DROP CONSTRAINT "FK_14ccdd74bf1a96986f6a9e1a4cd"`);
        await queryRunner.query(`ALTER TABLE "watchlists" DROP CONSTRAINT "FK_3e8bccad3dcd75fa977892c54bb"`);
        await queryRunner.query(`ALTER TABLE "price_alerts" DROP CONSTRAINT "FK_5c9e7ca80a3fdbfd7f1d08b30c3"`);
        await queryRunner.query(`ALTER TABLE "price_alerts" DROP CONSTRAINT "FK_e935431220d8759d650a506472f"`);
        await queryRunner.query(`ALTER TABLE "news_article_assets" DROP CONSTRAINT "FK_21d07060b26c5bedf54158c67d0"`);
        await queryRunner.query(`ALTER TABLE "news_article_assets" DROP CONSTRAINT "FK_a3ca2d90b92cb0d74e6ec063e85"`);
        await queryRunner.query(`ALTER TABLE "news_articles" DROP CONSTRAINT "FK_7a18c32abffd704bb30dd82d8d2"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_22a05e92f51a983475f9281d3b0"`);
        await queryRunner.query(`ALTER TABLE "user_suggestion_interactions" DROP CONSTRAINT "FK_7355d10e8e25f0bba9d5eac300c"`);
        await queryRunner.query(`ALTER TABLE "user_suggestion_interactions" DROP CONSTRAINT "FK_988a12e65c53a9692a54a54104f"`);
        await queryRunner.query(`ALTER TABLE "trade_suggestions" DROP CONSTRAINT "FK_c2807b88e83a63424931813a8b9"`);
        await queryRunner.query(`ALTER TABLE "trade_suggestions" DROP CONSTRAINT "FK_d41e829364b231f5f11327ab645"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_e6cbd271f04a4997030d2632cf3"`);
        await queryRunner.query(`ALTER TABLE "predictions" DROP CONSTRAINT "FK_f27be35e654b00363e7ae5c78fd"`);
        await queryRunner.query(`ALTER TABLE "user_preferences" DROP CONSTRAINT "FK_458057fa75b66e68a275647da2e"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88102539f457e6b871d794bf2d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af11df5cf61163ea71b7f54f51"`);
        await queryRunner.query(`DROP TABLE "api_request_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4578235c4831ec7f89308d4c8"`);
        await queryRunner.query(`DROP TABLE "external_api_usage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2bb2cd3da42b56a12729b919d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_966b24173414783279e5ed1d85"`);
        await queryRunner.query(`DROP TABLE "economic_events"`);
        await queryRunner.query(`DROP TYPE "public"."economic_events_impact_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52d89390506ed998a56a73c04c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0672782561e44d43febcfba298"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_feedback_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa209cf48ae975a109366542a"`);
        await queryRunner.query(`DROP TABLE "chat_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65fffed6d159417beffa3cfb00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06f082ac79ac86cbb475e1a8d5"`);
        await queryRunner.query(`DROP TABLE "kb_chunks"`);
        await queryRunner.query(`DROP TABLE "kb_documents"`);
        await queryRunner.query(`DROP INDEX "public"."idx_candle_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6cc46de572ad37ba5f5751001"`);
        await queryRunner.query(`DROP TABLE "ohlcv_candles"`);
        await queryRunner.query(`DROP TYPE "public"."ohlcv_candles_timeframe_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13f381b5af2e4065063d97cdd7"`);
        await queryRunner.query(`DROP TABLE "watchlists"`);
        await queryRunner.query(`DROP TABLE "price_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."price_alerts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."price_alerts_condition_enum"`);
        await queryRunner.query(`DROP TABLE "news_article_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b851c5ab8c02be5814e137be83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77c25997a64e1cc75db6f0cfdf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a18c32abffd704bb30dd82d8d"`);
        await queryRunner.query(`DROP TABLE "news_articles"`);
        await queryRunner.query(`DROP TABLE "news_sources"`);
        await queryRunner.query(`DROP TYPE "public"."news_sources_source_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea7720e04e3ae1278575c3159c"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."oauth_accounts_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5b41340eb4bba9fd21fab3524"`);
        await queryRunner.query(`DROP TABLE "user_suggestion_interactions"`);
        await queryRunner.query(`DROP TYPE "public"."user_suggestion_interactions_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a09a50a76cb6216696c834f9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2192c23b5304d5b5c91a0188c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2807b88e83a63424931813a8b"`);
        await queryRunner.query(`DROP TABLE "trade_suggestions"`);
        await queryRunner.query(`DROP TYPE "public"."trade_suggestions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trade_suggestions_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c394ecc1e8fa58f6580bf66afa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9128d7a79e536a2896637109ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f27be35e654b00363e7ae5c78f"`);
        await queryRunner.query(`DROP TABLE "predictions"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_actual_label_enum"`);
        await queryRunner.query(`DROP TYPE "public"."predictions_predicted_label_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaa6c65fe7cf634aa3d80f317d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b4bd5b9c6fe49cd3b4342fb91"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TYPE "public"."assets_asset_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11b873c6a08fbd8bacf23558bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9de8e07593325e4dce1f0c73a"`);
        await queryRunner.query(`DROP TABLE "ml_models"`);
        await queryRunner.query(`DROP TYPE "public"."ml_models_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ml_models_target_timeframe_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ml_models_asset_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_458057fa75b66e68a275647da2"`);
        await queryRunner.query(`DROP TABLE "user_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
